container_binary: docker # O 'podma', sto parametrizzando le scelte in questo file globale'

# Configurazione Utente e SSH
generic_user: "ansible_admin"
user_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61663934633366366132313036623163616434663433306239623134616230373666383238623166
          6564613664393338366437343037396138383630366262370a643939663938393064333565663964
          33313933613062383366303935613961393263633462633062343865666464376539373137626335
          3333646537633031310a386331346434353232363239373638363833663130343161386339653539
          6333
ssh_key_path: "{{ lookup('env', 'HOME') }}/.ssh/id_ansible_admin"

# Configurazione Registry
registry_name: "local_registry"
registry_port: 5000
registry_url: "localhost:{{ registry_port }}"

# Definizione Immagini da Costruire
build_images:
  - name: debian-ssh-server
    dockerfile: Dockerfile.debian
    os_type: debian
  - name: centos-ssh-server
    dockerfile: Dockerfile.centos
    os_type: centos

# Configurazione Deploy (Run)
# Qui definiamo le porte host per evitare conflitti (2221, 2222)
deploy_containers:
  - name: container_debian
    image: debian-ssh-server
    host_port: 2221
  - name: container_centos
    image: centos-ssh-server
    host_port: 2223
